const FETCH_ORGANIZATIONS = 'FETCH_ORGANIZATIONS';
// redux2: Exported FETCH_CAUSES, but not entirely sure why this is necessary
const FETCH_CAUSES = 'FETCH_CAUSES';
const UPDATE_SEARCH_TERMS = 'UPDATE_SEARCH_TERMS';
const UPDATE_SEARCH_RADIUS = 'UPDATE_SEARCH_RADIUS';
const UPDATE_SEARCH_CAUSES = 'UPDATE_SEARCH_CAUSES';
const FETCH_USER = 'FETCH_USER';
const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';

export const Actions = {
  FETCH_ORGANIZATIONS,
  // redux2: Exported FETCH_CAUSES, but not entirely sure why this is necessary
  FETCH_CAUSES,
  UPDATE_SEARCH_TERMS,
  UPDATE_SEARCH_RADIUS,
  UPDATE_SEARCH_CAUSES,
  FETCH_USER,
  FETCH_USER_SUCCESS
};